# Generated by Django 4.0.1 on 2022-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('TrackingNumber', models.CharField(max_length=50)),
                ('Customer', models.TextField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
