# Generated by Django 4.0.1 on 2022-02-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbound',
        ),
    ]
