# Generated by Django 4.0.1 on 2022-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managementsystem', '0002_delete_inbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('trackingNumber', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('outboundTracking', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
